site_name: ManiMorphs
theme:
  name: "material"
  favicon: img/favicon.ico
  logo: img/logo.png
nav:
  - Home: index.md
  - Maths:
    - Pre-Algebra:
      - Whole Numbers: maths/pre-algebra/whole-numbers.md
      - Integers: maths/pre-algebra/integers.md
