site_name: ManiMorphs
theme:
  name: "material"
  favicon: img/favicon.ico
  logo: img/logo.png
nav:
  - Home: index.md
  - Maths:
    - Pre-Algebra:
      - Whole Numbers: maths/pre-algebra/whole-numbers.md
      - Integers: maths/pre-algebra/integers.md
      - Number Concepts: maths/pre-algebra/foundational-number-concepts.md
      - Fractions: maths/pre-algebra/fractions.md
      - Ratios, Rates & Proportions: maths/pre-algebra/ratios-rates-and-proportions.md
      - Decimals: maths/pre-algebra/decimals.md
      - Percentages & Basic Statistics: maths/pre-algebra/percentages-and-basic-statistics.md
      - Measurement: maths/pre-algebra/measurement.md
